[theme]
base = "light"
primaryColor = "#105d50"
backgroundColor = "#eff2ee"
secondaryBackgroundColor = "#f5f7f3"
textColor = "#172d27"
font = "sans serif"

[server]
headless = true
maxUploadSize = 12
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
